spring:
  #h2 세팅
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

    #jpa 세팅
  jpa:
    hibernate:
      #ddl-auto: create #자동으로 탭을 만들어주는, 애플리케이션 실행 시점에 가지고 있는 테이블을 지우고 다시 생성
      ddl-auto: none #데이터를 한 번 넣어두면 계속 반복하여 DB의 데이터를 계속 쓸 수 있다.
    properties:
      hiberate:
        #show_sql: true #System.out에 출력
        format_sql: true

logging.level:
    org.hibernate.SQL: debug #JPA나 Hibernate가 생성하는 SQL이 모두 보이는, logger를 통해
    org.hibernate.type: trace